apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

  managedNodeGroup:
    - name: sopt
      instanceType: m5.large
      desiredCapacity: 3
      sopt: true
      